### PR TITLE
Metrics

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by cmckni3** [comment]
Any idea what's up with this branch @statianzo?

**Comment by statianzo** [comment]
@spkane was doing some work. Not sure where it ended up.

**Comment by cmckni3** [comment]
I might look into this one day. It looks neat and useful.

**Comment by spkane** [comment]
@cmckni3 Feel free to grab this and run with it. We got pretty far with this, and it was useable, but not perfect. It changed enough things that we never ended up merging it back in (and I don't think it is being used by anything anymore). We were attempting to expose more of the metrics and make it possible to get a chart image returned. I has also been long enough that there may be better ways to utilize the API nowadays.

**Comment by cmckni3** [comment]
@spkane I can pick it up whenever I find the time. I'm sure the NewRelic APIs have evolved quite a bit as well.

Do you remember which charts you implemented? I am guessing CPU and Memory.

**Pull request closed without merging**
